### ISSUE TITLE
Will 50 epoch be enough？

### ISSUE THREAD

**Issue by ghost** [imlab-uiip/lung-segmentation-3d#11]
hi. eclique. What is the numbers did you use？ 
Is it enough  epoch = 50 ？

**Comment by eclique** [comment]
Hi. Yes, I used 50. I believe, it is enough, but you can play with it and see what works best for your dataset.

**Comment by ghost** [comment]
Thanks. How many nii files do you use for training?

**Comment by eclique** [comment]
About 200.
