### ISSUE TITLE
do you have some suggestions in this situation of difference size data? 

### ISSUE THREAD

**Issue by qoqoh** [imlab-uiip/lung-segmentation-3d#2]
hello.  eclique. thank you for your sharing of the codes. I have a question. If the size of my input data is not your data size of 128*128*64, I have to crop or reshape my data into this size for training. But I feel this method might miss some important detailed information. So, do you have some suggestions in this situation of difference size data?

**Comment by eclique** [comment]
Hi @qoqoh, 
I would suggest simple image resizing. It's true that it disregards some information about the scan, but it should still work. I didn't investigate smarter ways to do the resizing.
