### ISSUE TITLE
data acquisition question

### ISSUE THREAD

**Issue by KiyoshiKAWASAKI** [imlab-uiip/lung-segmentation-3d#3]
Hi,

I checked your 3D lung segmentation repository and it is really amazing. We are now doing research on organ segmentation and believe your repository is a very good reference.

I see you mentioned in ReadMe that you are using private dataset and I guess we may not able to obtain the same dataset as you used? But also I find that there are some requirement on data format and ground truth file format, that I would like to ask whether you know any public dataset might have similar format as the one you used for this repository?

Thanks,
Jin

**Comment by eclique** [comment]
Hi Jin,
Unfortunately I don't know of any public datasets with labeled lung fields in CT.

@gakarak is this dataset still not released?
