### ISSUE TITLE
incomplete segmentation

### ISSUE THREAD

**Issue by hfarhidzadeh** [imlab-uiip/lung-segmentation-3d#5]
Hi,
 Have you seen any hole within the segmentation due to nodules or artifact? If yes, how do you get the perfect filled-out mask?

**Comment by eclique** [comment]
Hi @CSMEDEEP,
Yes some masks do have holes in them but I am not applying any post processing to fill them in. I guess the easiest way to do that would be to run graph traversal to find a connected component of 0's from one of the corners and fill in everything else with 1's. Another option to consider is morphological closing.
