### ISSUE TITLE
Questions about loading model

### ISSUE THREAD

**Issue by MarshalLeeeeee** [imlab-uiip/lung-segmentation-3d#7]
Hello,

I cannot run inference.py directly without changing a thing. I run in python3, and I do not know if it is the version that matters? It seems that there exists problem in loading the model, I guess.
![image](https://user-images.githubusercontent.com/20102422/39235213-e0a6a77e-48a7-11e8-8820-1b9f03ebd906.png)
Can you help me with my problem? I am a machine learning beginner and it may be a stupid problem and I will be glad to get your feedback!!

**Comment by MarshalLeeeeee** [comment]
I tried the other model with append_coords set as True, but it did not work either. :(

**Comment by eclique** [comment]
You are running out of memory on your GPU.

**Comment by MarshalLeeeeee** [comment]
Okay, thanks a lot. I will settle the problem and try again.
