### ISSUE TITLE
load model problem when run inference.py

### ISSUE THREAD

**Issue by QinLuo-lus** [imlab-uiip/lung-segmentation-3d#8]
Hello,
I also cannot run inference.py directly without changing a thing.
And then  I  trained  a new model , but it also cannot load successfully.
![loadproblem](https://user-images.githubusercontent.com/29687039/40618897-8dc9fdde-62c5-11e8-9f9f-7e80ab47d20d.jpg)
I run this on keras 2.0.8, tensorflow 1.0.0.
Can you help me with this problem? Thanks a lot.

**Comment by carlosmontoyamoya** [comment]
i had similar problem with inference.py. 

model_name = 'model.050.hdf5' 
model = load_model(model_name)

pred = model.predict(X, batch_size=1)[..., 1]
this is the error i have after training:
ValueError: Error when checking input: expected input_1 to have shape (128, 128, 64, 4) but got array with shape (128, 128, 64, 1)

**Comment by eclique** [comment]
I guess the problem is in incorrect use of `append_coords` variable. I've described what it does [here](https://github.com/imlab-uiip/lung-segmentation-3d/issues/6).
